Update the manual testing instruction
AY2122S1-CS2103-F09-3/tp pull request #541
Opened 2021-11-07 16:13 UTC by ZhaoPeiduo

Update the manual testing instruction for show command, which is not fully covered in UG.

Fix the issue that labResultPanel does not update when executing dellab command.

2021-11-07 16:22 UTC, erwinqxy requested changes

2021-11-07 16:22 UTC, erwinqxy commented on docs/DeveloperGuide.md
> +       Expected: First st is deleted from the list. Details of the deleted student shown in the result display box.
what is st here? is this a typo

2021-11-07 16:22 UTC, erwinqxy commented on docs/DeveloperGuide.md
> +    1. Other incorrect delete commands to try: `delete`, `delete x`,  (where x is larger than the list size)<br>
1. Other incorrect delete commands to try: `delete`, `delete x`, (where x is larger than the list size)<be>

- extra white space before the bracket

2021-11-07 16:22 UTC, erwinqxy commented on docs/DeveloperGuide.md
> +       * If the right panel is showing a student's lab results, a red `Lab1`tag  and a Lab card with title `Lab1`, actual score `-` and total score `20` is added.
`Lab1` tag

missing white space?

2021-11-07 23:45 UTC, ZhaoPeiduo commented on docs/DeveloperGuide.md
> +       Expected: First st is deleted from the list. Details of the deleted student shown in the result display box.
Yes, thanks for pointing that out

2021-11-08 00:16 UTC, reddevil1313 approved these changes
LGTM

2021-11-08 00:17 UTC, reddevil1313 approved these changes

2021-11-08 00:43 UTC, erwinqxy approved these changes

2021-11-08 00:44 UTC, erwinqxy approved these changes
LGTM

2021-11-08 00:44 UTC, merged